### Get Spotify Credentials
< {%
    request.variables.set("spotify_credentials", "M2JkZjhkYmE3ZTdjNGE0NjliMWY5ZTkxM2EyN2JlNmY6ZDczYWU0OGQyMjE5NDI2ZWJlZDMzN2M4MTNkNjNkNTI=")
%}

POST https://accounts.spotify.com/api/token?grant_type=client_credentials
Accept: application/json
Authorization: Basic {{spotify_credentials}}
Content-Type: application/x-www-form-urlencoded

> {%
       client.test("Status code is 200", function() {
           client.assert(response.status === 200, "Response status is not 200");
       });

       client.test("Theres a access_token", function () {
              client.assert(response.body.access_token !== undefined, "access_token is undefined");
       })

       client.global.set("spotify_token", response.body.access_token);
 %}

### Get a User's Playlists
GET https://api.spotify.com/v1/users/smedjan/playlists
Accept: application/json
Authorization: Bearer {{spotify_token}}
